"""
Django settings for hackchat project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*k+572*xq96k9^)qc_ue)2674_)y%eu!cnz7konj!ps!n(lqi4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Events',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hackchat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hackchat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'waterbottle',
        'USER': 'root',
        'PASSWORD': 'sqlsql',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ***** LOGGING CONFIGURATION

# See: https://docs.djangoproject.com/en/dev/topics/logging/#filters
L_FILTERS = {
    'require_debug_false': {
        '()': 'django.utils.log.RequireDebugFalse'
    },
}

# See: https://docs.djangoproject.com/en/dev/topics/logging/#formatters
L_FORMATTERS = {
    'all_details': {
        'format': '%(asctime)s %(levelname)s %(process)d|%(thread)d '
                  '%(name)s.%(funcName)s():%(lineno)d %(message)s'
    }
}

# See: https://docs.djangoproject.com/en/dev/topics/logging/#handlers
L_HANDLERS = {
    'default_handler': {
        # file-based
        'level': 'INFO',
        'formatter': 'all_details',
        'class': 'logging.FileHandler',
        'filename': '/var/log/waterbottle/backend.log',
    },
}

L_ACTIVE_HANDLERS = [
    'default_handler', 'stats_handler',
]

# See: https://docs.djangoproject.com/en/dev/topics/logging/#loggers
# The loggers have default level set at DEBUG on all environments. This will
# get filtered out at the handler level.
L_LOGGERS = {
    'Events': {
        'handlers': L_ACTIVE_HANDLERS,
        'level': 'DEBUG',
        'propagate': True,
    },
    'hackchat': {
        'handlers': L_ACTIVE_HANDLERS,
        'level': 'DEBUG',
        'propagate': True,
    },
}

# See: https://docs.djangoproject.com/en/dev/ref/settings/#logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': L_FORMATTERS,
    'filters': L_FILTERS,
    'handlers': L_HANDLERS,
    'loggers': L_LOGGERS,
}
# ***** END LOGGING CONFIGURATION




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/srv/static/'